[default]
extend-ignore-identifiers-re = [
  "splitted.*",
]

[default.extend-identifiers]
dows = "dows"
escapeable = "escapeable"
lits = "lits"
lits1 = "lits1"
lits2 = "lits2"
minimals_ids = "minimals_ids"
Nd = "Nd"
strat = "strat"
Welp = "Welp"

[default.extend-words]
ba = "ba"
BA = "BA"
fo = "fo"
Fo = "Fo"
FO = "FO"
escapeable = "escapeable"

[files]
extend-exclude = [
  "regex-automata/src/util/unicode_data/*.rs",
  "regex-syntax/src/unicode_tables/*.rs",
  "testdata/*.toml",
  "testdata/fowler/dat/*.dat",
  "testdata/fowler/*.toml",
  "regex-capi/examples/sherlock.txt",
  ]
