#!/bin/bash

# This is a convenience script for running a broad swath of tests across
# features. We don't test the complete space, since the complete space is quite
# large. Hopefully once we migrate the test suite to better infrastructure
# (like regex-automata), we'll be able to test more of the space.
echo "===== DEFAULT FEATURES ==="
cargo test

features=(
    "std perf"
    "std perf unicode-perl"
)
for f in "${features[@]}"; do
    echo "===== FEATURE: $f ==="
    cargo test --test default --no-default-features --features "$f"
done
