#!/bin/bash

set -e

# This is a convenience script for running a broad swath of the syntax tests.
echo "===== DEFAULT FEATURES ==="
cargo test

features=(
    std
    unicode
    unicode-age
    unicode-bool
    unicode-case
    unicode-gencat
    unicode-perl
    unicode-script
    unicode-segment
)
for f in "${features[@]}"; do
    echo "=== FEATURE: $f ==="
    # We only run library tests because I couldn't figure out how to easily
    # make doc tests run in 'no_std' mode. In particular, without the Error
    # trait, using '?' in doc tests seems tricky.
    cargo test --no-default-features --lib --features "$f"
done
