#!/bin/sh

# Enable SIMD.
export RUSTFLAGS="-C target-cpu=native"

exec cargo build \
  --release \
  --features 're-re2 re-onig re-pcre1 re-pcre2 re-rust re-rust-bytes re-tcl re-dphobos-dmd re-dphobos-ldc' \
  "$@"
