#!/bin/bash

usage() {
  echo "Usage: $(basename $0) [dphobos-dmd | dphobos-ldc | dphobos-dmd-ct | dphobos-ldc-ct | rust | rust-bytes | pcre1 | pcre2 | stdcpp | stdcpp-libcxx | boost | re2 | onig | tcl ]" >&2
  exit 1
}

if [ $# = 0 ] || [ $1 = '-h' ] || [ $1 = '--help' ]; then
  usage
fi

which="$1"
shift
case $which in
  dphobos-dmd)
    exec cargo bench --bench bench --features re-dphobos-dmd "$@"
    ;;
  dphobos-ldc)
    exec cargo bench --bench bench --features re-dphobos-ldc "$@"
    ;;
  dphobos-dmd-ct)
    exec cargo bench --bench bench --features re-dphobos-dmd-ct "$@"
    ;;
  dphobos-ldc-ct)
    exec cargo bench --bench bench --features re-dphobos-ldc-ct "$@"
    ;;
  rust)
    exec cargo bench --bench bench --features re-rust "$@"
    ;;
  rust-bytes)
    exec cargo bench --bench bench --features re-rust-bytes "$@"
    ;;
  stdcpp)
    exec cargo bench --bench bench --features re-stdcpp "$@"
    ;;
  stdcpp-libcxx)
    exec cargo bench --bench bench --features 're-stdcpp libcxx' "$@"
    ;;
  boost)
    exec cargo bench --bench bench --features re-boost "$@"
    ;;
  re2)
    exec cargo bench --bench bench --features re-re2 "$@"
    ;;
  pcre1)
    exec cargo bench --bench bench --features re-pcre1 "$@"
    ;;
  pcre2)
    exec cargo bench --bench bench --features re-pcre2 "$@"
    ;;
  onig)
    exec cargo bench --bench bench --features re-onig "$@"
    ;;
  tcl)
    exec cargo bench --bench bench --features re-tcl "$@"
    ;;
  *)
    usage
    ;;
esac
