#!/usr/bin/env python3

from subprocess import run
import datetime
import json
import os

PREAMBLE = """
// DO NOT EDIT. Automatically generated by 'scripts/public-traits-tests.py'
// on {date}.
""".lstrip()

CMD = [
    "cargo",
    "rustdoc",
    "-q",
    "--",
    "-Z",
    "unstable-options",
    "--output-format",
    "json",
]


def get_public_of_kind(kinds, elements, index):
    keys_of_kind = filter(lambda key: index[key]["kind"] in kinds, elements)
    public_of_kind = filter(
        lambda key: index[key]["visibility"] == "public", keys_of_kind
    )
    return map(lambda key: index[key], public_of_kind)


def gen_test(path):
    tests = [
        f"\tassert_send::<{path}>();",
        f"\tassert_sync::<{path}>();",
        f"\tassert_unwind_safe::<{path}>();",
        f"\tassert_ref_unwind_safe::<{path}>();",
        ""
    ]
    return "\n".join(tests)


def gen_tests():
    doc_gen_result = run(CMD)
    if doc_gen_result.returncode != 0:
        print("Unable to generate the docs for the regex")
        exit(1)

    with open(os.path.join("target", "doc", "regex.json")) as docs_file:
        docs = json.load(docs_file)
        index = docs["index"]

        tests = []
        public_modules = get_public_of_kind(["module"], index.keys(), index)
        for mod in public_modules:
            tests.append("")
            types = get_public_of_kind(["struct"], mod["inner"]["items"], index)
            for type in types:
                prefix = "" if mod["inner"]["is_crate"] else "regex::"
                test = gen_test(f"{prefix}{mod['name']}::{type['name']}")
                tests.append(test)

        return tests


def get_assert_definitions():
    definitions = [
        "\tfn assert_send<T: Send>() {}",
        "\tfn assert_sync<T: Sync>() {}",
        "\tfn assert_unwind_safe<T: UnwindSafe>() {}",
        "\tfn assert_ref_unwind_safe<T: RefUnwindSafe>() {}",
    ]
    return "\n".join(definitions)


def main():
    with open(os.path.join("tests", "marker_traits.rs"), "w") as f:
        f.write(PREAMBLE.format(date=str(datetime.datetime.now())))
        f.write("\n")
        f.write("#[test]\nfn marker_traits() {\n")
        f.write("\tuse std::panic::{RefUnwindSafe, UnwindSafe};\n")
        f.write("\n")
        f.write(get_assert_definitions())
        f.write("\n")
        for test in gen_tests():
            f.write(f"{test}\n")
        f.write("}\n")


if __name__ == "__main__":
    main()
